services:
  bonus_service:
    build: ./bonus-service
    env_file:
      - ./bonus-service/.env
    ports:
      - "3001:3000"
    depends_on:
      - kafka
      - managers_bonus_db

  managers_bonus_db:
    image: postgres:17.5-bookworm
    env_file:
      - ./bonus-service/.env
    ports:
      - "5431:5432"


  task_management_service:
    build: ./task-management-service
    env_file:
      - ./task-management-service/.env
    ports:
      - "3002:3000"
    depends_on:
      - kafka
      - task_management_db


  task_management_db:
    image: postgres:17.5-bookworm
    env_file:
      - ./task-management-service/.env
    ports:
      - "5432:5432"

  teacher_hiring_service:
    build: ./teacher-hiring-service
    env_file:
      - ./teacher-hiring-service/.env
    ports:
      - "3003:3000"
    depends_on:
      - kafka
      - task_management_db


  teacher_hiring_db:
    image: postgres:17.5-bookworm
    env_file:
      - ./teacher-hiring-service/.env
    ports:
      - "5433:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.15
    env_file:
      - .env-zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.2.15
    ports:
      - "9092:9092"
    env_file:
      - .env-kafka
    depends_on:
      - zookeeper