name: Setup NodeJS for service
inputs:
  node-version:
    description: "NodeJS version"
    required: true
  working-directory:
    description: "Path to service folder"
    required: false
    default: .

runs:
  using: 'composite'
  steps:
    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working-directory }}/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles(format('{0}/package-lock.json', inputs.working-directory)) }}
        restore-keys: ${{ runner.os }}-node

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
      shell: bash
      working-directory: ${{ inputs.working-directory }}
